"use client";

import jsPDF from "jspdf";
// Actually jspdf-autotable is a separate package. I'll stick to basic text or check if installed. 
// Package.json didn't show jspdf-autotable. I'll use simple text for now or install it.
// Let's implement basic text PDF first.

import { Download } from "lucide-react";

type ReportData = {
    studentName: string;
    admissionNo: string;
    className: string;
    exams: {
        name: string;
        subject: string;
        marks: number;
        total: number;
    }[];
};

export default function ReportCardDownload({ data }: { data: ReportData }) {
    const generatePDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.text("School Management System", 105, 20, { align: "center" });

        doc.setFontSize(16);
        doc.text("Report Card", 105, 30, { align: "center" });

        // Student Info
        doc.setFontSize(12);
        doc.text(`Name: ${data.studentName}`, 20, 50);
        doc.text(`Admission No: ${data.admissionNo}`, 20, 60);
        doc.text(`Class: ${data.className}`, 20, 70);

        // Marks Table Header
        let y = 90;
        doc.setFont("helvetica", "bold");
        doc.text("Subject", 20, y);
        doc.text("Exam", 80, y);
        doc.text("Marks Obtained", 140, y);
        doc.text("Total", 180, y);
        doc.line(20, y + 2, 190, y + 2);

        y += 10;
        doc.setFont("helvetica", "normal");

        data.exams.forEach(exam => {
            doc.text(exam.subject, 20, y);
            doc.text(exam.name, 80, y);
            doc.text(exam.marks.toString(), 140, y);
            doc.text(exam.total.toString(), 180, y);
            y += 10;
        });

        // Footer
        doc.line(20, 270, 190, 270);
        doc.setFontSize(10);
        doc.text("Generated by School Management System", 105, 280, { align: "center" });

        doc.save(`${data.admissionNo}_ReportCard.pdf`);
    };

    return (
        <button
            onClick={generatePDF}
            className="flex items-center space-x-2 bg-blue-900 text-white px-4 py-2 rounded hover:bg-blue-800"
        >
            <Download size={18} />
            <span>Download Report Card</span>
        </button>
    );
}
